### ISSUE TITLE
PaloAlto TinyBasic版 StarTrek が動くようにしたい

### ISSUE THREAD

**Issue by kikeroga3** [dolphilia/tinyhsp#1]
dolphiliaさん
TinyHSPプロジェクトの開設、まことにありがとうございます！
本家と異なる仕様ですが、システム変数「key」は良いアイデアだと思いました。

TinyHSPの進捗状況にあわせてになると存じますが、
PaloAlto TinyBasic版からの移植で
「dolphilia TinyHSP版 StarTrek」を作りたいと思っています(^_^)

ソースは以下からゲット
http://www.vector.co.jp/soft/screen/winnt/prog/se506722.html
Tiny版スタトレ、意外とみつけるのに手間取りました。。

では！(^_^)/

**Comment by dolphilia** [comment]
コメントありがとうございます。

TinyBASICといえば、StarTrekですよね。
ソースコードも探してくださり、
ありがとうございます。

**Comment by dolphilia** [comment]
Issuesの整理のためにCloseします。
