### ISSUE TITLE
[提案]変数名は固定にせず、型も動的なものにした方が良い

### ISSUE THREAD

**Issue by mjhd-devlion** [dolphilia/tinyhsp#2]
[掲示板](http://hsp.tv/play/pforum.php?mode=all&num=77515)の案とは趣旨が若干異なるようですので、関係ないと思ったらCloseしていただいて構いません。

提案なのですが、変数が27個だけというのは制限しすぎなような気がします。
また、HSPはせっかく動的型付け言語なので、そこも削ってしまうのは「BASICとして軽量な言語」という別のテーマになってしまいそうな気がします。
変数名、型の決定などは本家HSPと同じような仕様にした方が自由度・HSPらしさがあってよいのでは？という提案です。

**Comment by dolphilia** [comment]
貴重な提案ありがとうございます。

変数を動的なものにするというのは良い案だと思います。
参考にさせていただきます。

**Comment by kikeroga3** [comment]
抽象的ですが"HSPらしさ"のような特徴はあると良いですね。

**Comment by dolphilia** [comment]
Issuesの整理のためにCloseします。
