### ISSUE TITLE
TinyHSPのマスコットイメージ

### ISSUE THREAD

**Issue by kikeroga3** [dolphilia/tinyhsp#4]
プロフにあるdolphiliaさんのイラストがとても可愛らしくて良いイメージなので、
お作りのTinyHSPもしくはその後に予定しているクリーンHSPのマスコットに使われては？
と思いました。
イメージは大切かと。

板汚しになっておりましたら整理してくださいm(_ _)m

**Comment by dolphilia** [comment]
こんな感じでしょうか。

![miyuzu](https://cloud.githubusercontent.com/assets/13228693/22172736/56d7206a-dff2-11e6-8ca8-ea155caf7acf.jpg)

**Comment by kikeroga3** [comment]
そんな感じで～す！

**Comment by dolphilia** [comment]
![miyuzu_header](https://cloud.githubusercontent.com/assets/13228693/22240053/9dba8334-e25c-11e6-8543-7a537abf6664.png)

ヘッダー的なものを描きました。

**Comment by kikeroga3** [comment]
おほッ！ちょーカワイイですな！！"TinyHSP"にぴったりな雰囲気ですよ。
お名前はチニーちゃんとか？ティノちゃんとか？
こういうイメージも含めて進めていくと楽しいですよね(^o^)
易しそうなイメージ作りにも貢献しそうです。

**Comment by kikeroga3** [comment]
愉しく試行錯誤されてるようで、イイ感じですね(^_^)

プロトタイプをどんどん作っていくというのは
手早く動作感覚をつかめて面白いアプローチですね。

ピンときたプロトタイプがあれば正式に取りかかるって手法ですかね？

**Comment by dolphilia** [comment]
コメントありがとうございます。

私はおもに、
小さな達成感のために、プロトタイプを作っています。

「よし、今日もプロトタイプが完成したぞ」と思えると、
達成感があり、モチベーションの維持に役立つように感じています。

イラストの女の子の名前は「折原みゆず」です。
「みゅーたん」とか「みゅーちゃん」と呼ばれています。

[公式サイト](http://miyuzu.com)もあります。

**Comment by kikeroga3** [comment]
確かにモチベーション維持するにはイイ方法ですね。

「tinyhsp.exe」も付けていただけると、こちらでもテストが出来たりして、
ちょいと嬉しいかもしれません。
MinGW(gcc)でも自分で入れれば出来るのかな？

ともあれdolphilia版TinyHSPでStarTrekが作れる日を心待ちにしております！
みゅーたんのファンになりました(^o^)/
