### ISSUE TITLE
TinyHSPで作ったプログラム

### ISSUE THREAD

**Issue by kikeroga3** [dolphilia/tinyhsp#6]
(お約束？の)TinyHSP版StarTrekができたのでお伝えします(^_^)/

ソーススクリプト
https://github.com/kikeroga3/tinyhsp/blob/master/extra/tinytrek.hs

この等幅フォントが必要
https://github.com/kikeroga3/tinyhsp/blob/master/extra/tiny_en.ttf

ちなみに11号用です。

9号で作ることも可能だと考えたのですが、楽な方向に転がりました。

**Comment by dolphilia** [comment]
ご報告ありがとうございます。

macOSでも正常に動作しました。

![tinytrek](https://cloud.githubusercontent.com/assets/13228693/23113511/f92e7282-f77b-11e6-9a77-5a2740cf2cfb.png)

TinyHSPというとてもコンパクトな処理系で、
よくぞ作られたと感心しています。

**Comment by dolphilia** [comment]
tinytrek.hsのほか、
同封のサンプルスクリプトも遊んでみました。

どれも面白かったのですが、
特にkakiget.hsやlanding.hsは、
ちゃんとミニゲームとして遊べるところが良かったです。

StarTrekも含めて楽しいスクリプトをありがとうございます。

**Comment by kikeroga3** [comment]
> macOSでも正常に動作しました。

想定通りとはいえクロスプラットフォームが立証されるのは嬉しいですね(^_^)

小さくシンプル、クロスプラットフォーム、
TinyHSPには、えも言われぬ魅力がひそんでいると思ってます。

飽きたらあっさりやめるとは思うのですが、とりあえず今は
この楽しさを伝えたいという思いから、時流に関係なく、地道に
楽しみながら普及活動してみたいと思っています。
