### ISSUE TITLE
進み具合の報告2

### ISSUE THREAD

**Issue by dolphilia** [dolphilia/tinyhsp#7]
主に進み具合を報告するスレッドとして使います。また、考えていることを書き込んだり、画像の貼り付けに使ったりするかもしれません。TinyHSPに関係のないことを書き込むかもしれません。どなたでも自由に書き込んでくださって構いません。

前のIssues #5

**Comment by dolphilia** [comment]
プロトタイプ13号はTinyHSPのC言語移植版です。

**Comment by dolphilia** [comment]
プロトタイプ14号はTinyHSP拡張版のC言語移植版です。

![default](https://cloud.githubusercontent.com/assets/13228693/24576292/3e383c18-16f4-11e7-926b-c6c4d0690525.PNG)

**Comment by dolphilia** [comment]
プロトタイプ14号にwave命令を加えました。
OpenALを使用して、各種波形を再生します。

使い方：

`wave p1, p2, p3, p4`

- p1: 初期値は440。再生する周波数を指定する
- p2: 初期値は1000。再生時間をミリ秒単位で指定する
- p3: 初期値は0。波形の種類を0～4で指定する。
  - 0: 正弦波
  - 1: ノコギリ波
  - 2: 矩形波
  - 3: 三角波
  - 4: 白雑音
- p4: 初期値は3000。ボリュームを0～30000程度で指定する。

**Comment by kikeroga3** [comment]
おお、プロトタイプ14号！？OpenAL！wave命令！
新たな展開に期待しております！

tinyhsp.exe をちょっと試させていただきましたところ
「VCRUNTIME14D.dll がありません」とか言われました。

時間のあるときにMinGWでコンパイルしてみようと思います。

**Comment by dolphilia** [comment]
コメントありがとうございます。

今回はVisual Studio Community 2015でコンパイルしたので、
「Visual Studio 2015 の Visual C++ 再頒布可能パッケージ」をインストールすると、解決するかもしれません。

入手先：
https://www.microsoft.com/ja-JP/download/details.aspx?id=48145

---

MinGWでコンパイルしたバージョンのバイナリを以下にアップロードしました。
https://github.com/dolphilia/tinyhsp/releases
`tinyhsp_ex_20170402.zip` が該当のバイナリです。

エラーメッセージは文字コードの関係で文字化けします。
CuteHSPのようにメッセージを英字にするのが良い解決策なのかな、と思います。

---

**プロトタイプ14号をMinGWでコンパイルする方法：**

まずOpenALを入手します。
https://openal.org/downloads/

- OpenAL 1.1 Core SDK (zip)
- OpenAL 1.1 Windows Installer (zip)

上記の２つのファイルをダウンロードして解凍、
インストーラを実行してインストールします。

「OpenAL 1.1 Core SDK」をインストールすると、

`C:\Program Files` か `C:\Program Files(x86)` に、
`OpenAL 1.1 SDK` というフォルダが作成されます。

その中にある、
`include` フォルダ内のファイル を　MinGWの `include` フォルダにコピーします。
また、
`libs\Win32` フォルダ内のファイルを　MinGWの `lib` フォルダにコピーします。

「OpenAL 1.1 Windows Installer (zip)」をインストールすると、
`C:\Windows\System32` フォルダ内と、
`C:\Windows\SysWOW64` フォルダ内に、
`OpenAL32.dll` がインストールされますので、
それプロジェクトフォルダにコピーして使います。
（どちらを使用すべきなのかは、現状不明です;^^）

なおOpenALのライセンスはLGPLです。
今回は「動的リンク」かつ「DLLを同封」なので、
TinyHSP自体は引き続きMITライセンスを使用できるはずです。

また、OpenALのソースを配布、あるいはリンクなどを公開する必要があるようです。

参考：http://atmarksharp.v01.jp/posts/lgpl-dynamic-link.html

**Comment by kikeroga3** [comment]
鳴りました！MinGWでコンパイルしたバージョンはVCランタイム不要みたいですね。
OpenALの導入も勉強させていただきます。
いつもありがとうございます！ほんと助かってます(^o^)

**Comment by kikeroga3** [comment]
14号のwave命令を試してみましたが、以下(Star Wars)が曲になっていませんでした。
(第3パラメータを変えても同じ)
beepとは音階(周波数)指定値が違うんでしょうか？

wave 440,500,1
wave 440,500,1
wave 440,500,1
wave 349,350,1
wave 523,150,1
wave 440,500,1
wave 349,350,1
wave 523,150,1
wave 440,1000,1
wave 659,500,1
wave 659,500,1
wave 659,500,1
wave 698,350,1
wave 523,150,1
wave 415,500,1
wave 349,350,1
wave 523,150,1
wave 440,1000,1
wave 880,500,1
wave 440,350,1
wave 440,150,1
wave 880,500,1
wave 830,250,1
wave 784,250,1
wave 740,125,1
wave 698,125,1
wave 740,250,1
wave 455,250,1
wave 622,500,1
wave 587,250,1
wave 554,250,1
wave 523,125,1
wave 466,125,1
wave 523,250,1
wave 349,125,1
wave 415,500,1
wave 349,375,1
wave 440,125,1
wave 523,500,1
wave 440,375,1
wave 523,125,1
wave 659,1000,1
wave 880,500,1
wave 440,350,1
wave 440,150,1
wave 880,500,1
wave 830,250,1
wave 784,250,1
wave 740,125,1
wave 698,125,1
wave 740,250,1
wave 455,250,1
wave 622,500,1
wave 587,250,1
wave 554,250,1
wave 523,125,1
wave 466,125,1
wave 523,250,1
wave 349,250,1
wave 415,500,1
wave 349,375,1
wave 523,125,1
wave 440,500,1
wave 349,375,1
wave 261,125,1
wave 440,1000,1

**Comment by kikeroga3** [comment]
ばっちり演奏されております！

**Comment by kikeroga3** [comment]
ソースひとつにまとめたんですね。なんだかすっきりしましたね。
Ｃ言語に移植した意図は何でしょうか？
よろしければおしえてください。

**Comment by dolphilia** [comment]
動作確認ありがとうございます。
正常動作したとのことで、安心しました。

---

C言語に移植した理由は2つあります。

**１つ目の理由**は、
保守しやすくするためです。（あくまで私の場合です）

私にとってC\+\+はとても難しい言語です。

私はC\+\+の機能をよく理解していません。
（C言語も「理解した」と言えるほど分かってはいませんが・・・;^^）

それで、もし将来的に、
TinyHSPのコア部分にバグが見つかった場合に、
私の手に負えなくなるリスクを少しでも減らしたいと思いました。

C言語とC\+\+、
どちらが自分にとって保守しやすいか考えたときに、
私の場合はC言語だったということです。

（というのはたぶん建前で、
　正直なところは「ごめん、C\+\+は分からない」です。
　謙遜とかじゃなく、本当に分かっていないのです;^^）

**２つ目の理由**は、
移植に備えるためです。

iOSアプリを例にします。

iOSアプリを作るためには、
Objective-Cという言語を使う必要があります。（今はSwiftという言語もあります）
CやC\+\+のみでiOSアプリを作ることは基本的にできません。

Objective-C\+\+という言語も使うことができます。
それはCとC\+\+とObjective-Cが混在したような言語です。
C\+\+のコードをiOSに移植したいときは、これを使います。

想像に難くないと思いますが、
CとC\+\+とObjective-Cが混在した状態でコーディングしていくと、
もう訳が分からなくなってしまいます。;^^

macOS版HSPのコード抜粋：
（C\+\+とObjective-Cが混在している）

```objective-c++
CAutoSbFree::~CAutoSbFree() {
    sbFree(*pptr_);
}

@implementation ViewController (hsp3int)

//----Sort Routines
- (bool)less_int_1:(DATA const &)lhs rhs:(DATA const &)rhs {
    int cmp = (lhs.as.ikey - rhs.as.ikey);
    return (cmp < 0) || (cmp == 0 && lhs.info < rhs.info);
}
```

それで多少でも負担を減らすために、
一旦C\+\+をCに移植するのは良いことだと判断しました。

---

私の考えがきちんと伝わったか、心配です。;^^

**Comment by kikeroga3** [comment]
dolphiliaさんのお考えをきちんと理解できてるのかどうかは怪しいですが、
C++が読みにくく、C言語が保守しやすい、移植しやすいというのは
とても納得のいく理由です。
（そんなこと言いつつC言語化できちゃうのもスゴイと思いますが…）
お答え、ありがとうございました。

**Comment by dolphilia** [comment]
ご指摘ありがとうございます。
該当の2箇所を修正しました。

文字化けの不具合も修正しました（現状はVisualStudio2017のみ）。
VisualStudioでランタイムを必要としないビルドができるようなので、試してみました。
https://github.com/dolphilia/tinyhsp/releases/tag/1.0.3

スクリプトをドラッグ＆ドロップで実行できるようにして、
動作をCuteHSPに近づけました。

**Comment by kikeroga3** [comment]
試しましたが、残念ながら出ましたですね。
![tinyhsp_vcr_err](https://cloud.githubusercontent.com/assets/24917310/24744781/1d51e924-1aee-11e7-9f2d-55dca25e52e0.png)
CUI版のみ無事動作しておりました。

**Comment by dolphilia** [comment]
報告ありがとうございます。

私の方でも他に色々と試しましたがだめでした。
（MinGW64やEmbarcaderoのコンパイラ、MSYS2のGCCなど）

最終的に、
エラーメッセージをCuteHSPのものに差し替えさせていただき、
MinGWでコンパイルし直すことにしました。

https://github.com/dolphilia/tinyhsp/releases/tag/1.0.4

CuteHSPから以下のものも使用させていただきました。

- poke命令
- peek関数
- 一部のif条件分岐

**Comment by kikeroga3** [comment]
dolphiliaさん、ありがとうございます。
お世話になってばかりですので少しでもお役にたてたら嬉しいです。
実のところpeek,pokeもC言語化してくれないかなーとか思っていました(^^
bload,peek,pokeは共通に使えるほうがよさそうですね。

**Comment by dolphilia** [comment]
ご指摘ありがとうございます。
該当の箇所を修正しました。

---

circle命令を追加しました。
https://github.com/dolphilia/tinyhsp/releases/tag/1.0.5

標準版、拡張版で使用できます。

現状では、パラメータ5は1で固定しています。
塗りつぶしのみ可能です。

![default](https://cloud.githubusercontent.com/assets/13228693/24852237/be317712-1e11-11e7-8ebc-20d38370b87f.PNG)

**Comment by dolphilia** [comment]
macOSのRetina（高解像度）モードで実行すると、
表示が小さくなってしまう。

最近のMacはほとんどRetinaが標準になっているので、
修正しなくては・・・。

![retina_tinytrek_hs](https://cloud.githubusercontent.com/assets/13228693/24996478/00653e26-206e-11e7-871a-c2656dd43d2c.png)

**Comment by kikeroga3** [comment]
これはウィンドウ画面は640×480ドットなんですよね？

**Comment by dolphilia** [comment]
<img width="752" alt="2017-04-14 17 30 29" src="https://cloud.githubusercontent.com/assets/13228693/25038162/2d8ad256-2138-11e7-91b0-4e6305e87b91.png">

**Comment by kikeroga3** [comment]
ありがとうございます。こちらも対応したいと思います。

**Comment by kikeroga3** [comment]
更新されてるソース(tinyhsp.c)を拝見しました。
TinyをさらにTinyに、という目論見でしょうか？除外してる命令が天才的です！
さらに削るのであればエラー処理すら最小限でいいのでは？と思ったりもしましたが、
利用させていただく一ユーザとしてdim等をなくすのであれば
配列変数の要素数がデフォルトで16要素というのは少ないので
もうちょっと増やしておいたほうがいいのでは？と思いました。
勘違いしてたらゴメンナサイ(^_^)

**Comment by dolphilia** [comment]
コメントありがとうございます。

小さい方のtinyhsp.cは、
主に言語処理系に興味がある人向けに作りました。（自分のためですね^^）

読解しやすくするために、できるだけ小さくしています。
命令と関数はmesとrndだけを残しました。システム変数はcntだけです。
（randomizeした状態で実行されます）

またエラー処理は学習者にとって有用な情報なので残しました。
（どのようにエラーを検出しているかを学べるので）

この小さいtinyhsp.cを何かに使うことは想定していなかったのですが、
その方向性で使うために、配列の要素数を増やすのは良いアイデアだと思ったので、
初期値を512に増やしました。

**Comment by kikeroga3** [comment]
…まさに最軽量、まさにTinyHSPですね。

そういう観点だと確かにrandomizeも内部処理しておけば、わざわざ命令としては要らないですね。
我ながら既成概念に捕らわれてるなーと思い知りました(^^;
素晴らしいです。

初期値も豪快にふやしていただき、ありがとうございました。

**Comment by dolphilia** [comment]
[neteruhsp](https://github.com/exrd/neteruhsp)が更新されて、VMが搭載されたようです。
以前は抽象構文木を直接解析・実行していたのを、バイトコードに変換してから実行するようになっています。
本家HSPやJAVAのようにバイトコードをファイルに出力するのではなく、内部での実装です。

**Comment by kikeroga3** [comment]
処理速度に効果があるんですかね…2倍？3倍？それとも10倍くらい上がる？
命令を実行する関数は変わってないようですが。

**Comment by dolphilia** [comment]
次のコードを試してみました。

```
sum = 0
repeat 1000000
sum = abs(sum +cnt)
loop
```
VMなし: 3.66秒
VMあり: 1.66秒

VM搭載版の方が2.2倍ほど速いようです。

**Comment by kikeroga3** [comment]
あらら、すみません。お忙しい中、ありがとうございます。

VM対応で2倍くらいというのはソースの改修度合でも納得感ありますね。
でも2倍以上なら十分やる価値はありそうです。

おまけのほうはC言語が45倍速いですが、HSPが思ったよりも速くて感心してしまいました。
さすがおにたま氏というか…たぶん開発当初から処理速度は意識してチューンしてるんだろうなと。

**Comment by dolphilia** [comment]
追加情報です。

上はVisualStudioのDebugビルドでのテストでしたので、
Releaseビルドで（最適化をONにして）再度試してみました。

VMなし: 0.35秒
VMあり: 0.37秒

結果は僅差となりました。

「あれ？　おかしいな・・・」と、どうしてだろう考えていたところ、
[neteruhspがさらに新しくなっていた](https://github.com/exrd/neteruhsp)ので、
再び新しいneteruhspとVMなしの速度を測ってみました。

VMなし: 0.35秒
VMあり: 0.08秒

新しいVMあり版の方が4.37倍ほど速いようです。

**Comment by kikeroga3** [comment]
ありゃりゃ、最適化すると本家HSPと変わらない速度ですね(^^;
VM有無の差が4倍強と、、、単純化した中間コードでまわすとけっこうな効果がでるんですね。
しかし、それ以上にコンパイルオプションの最適化(-O？)でこれほどの速度差がでるとは知りませんでした。
gccやMinGWでも使えると思うので、参考にさせていただきます。

**Comment by dolphilia** [comment]
v1.0.6をリリースしました。
https://github.com/dolphilia/tinyhsp/releases

mmload, mmplay, mmstopを追加しました。

- mmload: p1に拡張子を含めたファイルを指定する。拡張子は.wavか.oggを使用できる。p2はループ再生するかをしていする。0がループなしで1がループ再生。デフォルトは0。
- mmplay: mmloadで読み込んだファイルを再生する。mmloadで読み込んでいない場合はエラー。
- mmstop: 再生中の音声を停止する。

本家HSPのように複数のバッファは用意していないので、今のところ重ねて再生することはできません。（wave命令は例外的に重ねて再生できます）。

---

拡張版のコンパイル方法が変わりました。

- `$ gcc -c tinyhsp.c stb_vorbis.c`
- `$ gcc tinyhsp.o stb_vorbis.o -o tinyhsp_ext -lopengl32 -lglfw3dll -lopenal32 -mwindows`

一旦オブジェクトファイルを作成してから、結合する感じです。

---

最適化も奥が深そうですね。

**Comment by kikeroga3** [comment]
mmplay実装ですか、なんだか最小の…というより若干CleanHSPな感じがしてきてるような(^^

**Comment by dolphilia** [comment]
TinyHSPはCleanHSPに近づいているのでしょうか。;^^
拡張版が、実はCleanHSPの基礎だったりするのでしょうか。

（すみません。自分でも意味不明なことを書いています）

---

mmplayについては、
導入コストの関係で採用することにしました。

本当は、MMLを演奏できる
PC-98のN88-BASICでいうところの「PLAY」命令のようなものが欲しかったのですが、
時代の流れには逆らえませんでした。;^^

**Comment by kikeroga3** [comment]
確かにMMLとかMIDIできたら良さそうですね～(^^)
でも実装もクロスプラットフォームも大変そうなのもわかります。

**Comment by kikeroga3** [comment]
ちなみに、paint命令を実装するのは難しいですか？

**Comment by dolphilia** [comment]
単純な塗りつぶしならできるかもしれません。

「塗りつぶし　アルゴリズム」などと検索して調べてみたところ、
スタックを使うものと、あるいは再帰のみで行なうものが見つかりました。

C言語はスタックを自前で実装する手間があるので、前者は見送りました。
再帰のみで行なう後者のアルゴリズムを試してみます。

tinyhsp.c 1898行目から

```c
//グローバル変数
int paint_buffer[640][480];

bool is_equal_color(color_t color_a, color_t color_b) {
	if (color_a.red == color_b.red &&
		color_a.green == color_b.green &&
		color_a.blue == color_b.blue) {
		return true;
	}
	else {
		return false;
	}
}

void set_paint(int x, int y, color_t paint_color) {
	if (x < 0 || y < 0 || x > screen_width || y > screen_height) {
		return;
	}
	// 点を打つ、バッファも打つ
	set_pixel_rgb(pixel_data, x, y, current_color_r, current_color_g, current_color_b, screen_width, screen_height);
	paint_buffer[x][y] = 1;
	// 左マス
	if (x - 1 >= 0) {
		if (is_equal_color(paint_color, get_pixel_color(pixel_data, x - 1, y, screen_width, screen_height)) &&
			paint_buffer[x - 1][y] == 0) {
			set_paint(x - 1, y, paint_color);
		}
	}
	// 上マス
	if (y - 1 >= 0) {
		if (is_equal_color(paint_color, get_pixel_color(pixel_data, x, y - 1, screen_width, screen_height)) &&
			paint_buffer[x][y - 1] == 0) {
			set_paint(x, y - 1, paint_color);
		}
	}
	// 右マス
	if (x + 1 <= screen_width) {
		if (is_equal_color(paint_color, get_pixel_color(pixel_data, x + 1, y, screen_width, screen_height)) &&
			paint_buffer[x + 1][y] == 0) {
			set_paint(x + 1, y, paint_color);
		}
	}
	// 下マス
	if (y + 1 <= screen_height) {
		if (is_equal_color(paint_color, get_pixel_color(pixel_data, x, y + 1, screen_width, screen_height)) &&
			paint_buffer[x][y + 1] == 0) {
			set_paint(x, y + 1, paint_color);
		}
	}
}

void
command_paint(execute_environment_t* e, execute_status_t* s, int arg_num)
{
	if (arg_num != 2) {
		raise_error("pos: Invalid argument."); // pos：引数が足りないか、多すぎます
	}
	const int arg_start = -arg_num;
	const value_t* p1 = stack_peek(s->stack_, arg_start);
	const int x = value_calc_int(p1);
	const value_t* p2 = stack_peek(s->stack_, arg_start + 1);
	const int y = value_calc_int(p2);
	// 塗りつぶし用バッファを初期化
	for (int y = 0; y < 480; y++) {
		for (int x = 0; x < 640; x++) {
			paint_buffer[x][y] = 0;
		}
	}
	// 塗りつぶす対象の色を特定
	color_t paint_color = get_pixel_color(pixel_data, x, y, screen_width, screen_height);
	// 塗りつぶす色を指定
	color_t current_color;
	current_color.red = current_color_r;
	current_color.green = current_color_g;
	current_color.blue = current_color_b;	
	// 塗りつぶし
	set_paint(x, y, paint_color);
	if (redraw_flag) {
		redraw();
	}
	stack_pop(s->stack_, arg_num);
}
```

アルゴリズムをざっくりと説明すると、
指定したピクセルを塗りつつ、そのピクセルの左右上下を調べ、

1. すでに塗られているピクセルに遭遇するか
2. 指定した最初のピクセルと違う色に遭遇するか
3. ウィンドウの外に出るか

するまで再帰し続ける感じです。
・・・アルゴリズムを言葉で説明しようとすると難しいですね。;^^

これの注意点は、これを普通にコンパイルして画面サイズ640x480いっぱいに塗りつぶそうとすると、
再帰がたくさん発生してスタックオーバーフローのエラーが発生することです。

（確認したのはWindowsのみです。他のOSでどうなるのかは分かりません）

それを防ぐために、MinGWの場合は、
`gcc tinyhsp.c -o tinyhsp_std -lopengl32 -lglfw3dll -mwindows -Wl,-stack,16777216`
などとプログラムのスタックサイズを指定してコンパイルする必要があるようです。
（16777216 = 16MB）

このプログラムで以下のスクリプトを実行してみます。

```
title "HelloWorld"
color 255,0,0
line 30,30,300,30
line 30,30,30,300
line 300,30,30,300
color 0,255,0
paint 40,40
color 0,0,255
paint 1,1
stop
```

![default](https://cloud.githubusercontent.com/assets/13228693/26143084/613d13de-3b1e-11e7-9cc6-3fe25121f412.PNG)

とりあえずは塗りつぶせている感じです。

**Comment by kikeroga3** [comment]
素晴らしい！勉強させていただきますm(_ _)m
ついに本家HSPにも存在しない命令を実装ですね(^^
本には間に合いませんでしたが、おってCuteのほうにも反映させていただきたいと思います。
このプログラムをみるとpget命令もついでにできちゃいそうですね。

**Comment by kikeroga3** [comment]
Lubuntu環境でコンパイルを試してみましたが、どーも
スタックサイズ指定ができない(おそらくmacOSも)みたいなので
時間があるときに下記のアルゴリズムを試してみようと思います。
http://fussy.web.fc2.com/algo/algo3-1.htm

**Comment by kikeroga3** [comment]
やってみました。
動いてはいますが、実はよく理解できてません(^^;

<pre>
// paint命令用
struct BufStr {
	int sx; /* 領域右端のX座標 */
	int sy; /* 領域のY座標 */
};
struct BufStr buff[1024]; /* シード登録用バッファ */
struct BufStr *sIdx, *eIdx;  /* buffの先頭・末尾ポインタ */


/* 点描画用関数 */
void dot_set(int x, int y, unsigned int col)
{
	unsigned int col_r = col / 65536;
	unsigned int col_g = (col & 0x00ff00) / 256;
	unsigned int col_b = col;
	set_pixel_rgb(pixel_data, x, y, col_r, col_g, col_b, screen_width, screen_height);
}

/* 色コードの取得 */
unsigned int dot_get(int x, int y)
{
	color_t col = get_pixel_color(pixel_data, x, y, screen_width, screen_height);
	return (65536 * col.red + 256 * col.green + col.blue);
}

/* 線分からシードを探索してバッファに登録する */
void scanLine(int lx, int rx, int y, unsigned int col)
{
	while (lx <= rx) {
		/* 非領域色を飛ばす */
		for (; lx <= rx ; lx++)
			if (dot_get(lx, y) == col) break;
		if (dot_get(lx, y) != col) break;
		/* 領域色を飛ばす */
		for (; lx <= rx ; lx++)
			if (dot_get(lx, y) != col) break;
		eIdx->sx = lx - 1;
		eIdx->sy = y;
		if (++eIdx == &buff[1024]) eIdx = buff;
	}
}

void
command_paint(execute_environment_t* e, execute_status_t* s, int arg_num)
{
	if (arg_num != 2) raise_error("paint: Invalid argument.");

	const int arg_start = -arg_num;
	const value_t* p1 = stack_peek(s->stack_, arg_start);
	const int x = value_calc_int(p1);
	const value_t* p2 = stack_peek(s->stack_, arg_start + 1);
	const int y = value_calc_int(p2);
	// 閉領域の色(領域色)
	unsigned int col = dot_get(x, y);
	// 塗り潰す時の色(描画色)
	unsigned int paintCol = 65536 * current_color_r + 256 * current_color_g + current_color_b;
	// 領域色と描画色が等しければ処理不要
	if (col == paintCol) return;

	int lx, rx; // 塗り潰す線分の両端のX座標
	int ly;     // 塗り潰す線分のY座標
	int i;

	sIdx = buff;
	eIdx = buff + 1;
	sIdx->sx = x;
	sIdx->sy = y;

	do {
		lx = rx = sIdx->sx;
		ly = sIdx->sy;
		if (++sIdx == &buff[1024]) sIdx = buff;
		// 処理済のシードなら無視
		if (dot_get(lx, ly) != col) continue;
		// 右方向の境界を探す
		while (rx < 639) {
			if (dot_get(rx + 1, ly) != col) break;
			rx++;
		}
		// 左方向の境界を探す
		while (lx > 0) {
			if (dot_get(lx - 1, ly) != col) break;
			lx--;
		}
		// lx-rxの線分を描画
		for (i = lx ; i <= rx ; i++)
			dot_set(i, ly, paintCol);
		// 真上のスキャンラインを走査する
		if (ly - 1 >= 0)
			scanLine(lx, rx, ly - 1, col);
		// 真下のスキャンラインを走査する
		if (ly + 1 <= 479)
			scanLine(lx, rx, ly + 1, col);
	} while ( sIdx != eIdx );

	if (redraw_flag) redraw();
	stack_pop(s->stack_, arg_num);
}
</pre>
これからLinuxでも試してみます。

**Comment by dolphilia** [comment]
ご報告ありがとうございます！

塗りつぶしアルゴリズムなどの、
目に見えるアルゴリズムはとても面白い分野なので、
じゃんじゃんトライしていただければと思います！

**Comment by dolphilia** [comment]
v1.0.7をリリースしました。

- 画面の下部1ピクセルが描画されない不具合を修正
- デフォルトの解像度を160x120に変更（ウィンドウサイズは640x480）

![2](https://cloud.githubusercontent.com/assets/13228693/26387087/d9785162-4085-11e7-85fa-3afddf83b0df.PNG)

スタックが1MBのまま再帰塗りつぶししても、
スタックオーバーフローしない解像度です。

![3](https://cloud.githubusercontent.com/assets/13228693/26387166/50c4cc32-4086-11e7-9feb-3ab31bf4fc45.PNG)

TinyPaintもレトロな感じになりました。

解像度を640x480に戻すには、
120行目あたりにある記述を次のように変更します。

```
#define SCREEN_WIDTH 640 // 画面解像度の幅と高さ
#define SCREEN_HEIGHT 480
#define MAGNIFICATION 1 // 倍率 = WINDOW_WIDTH / SCREEN_WIDTH
```

解像度を320x240にするには、次のように変更します。

```
#define SCREEN_WIDTH 320 // 画面解像度の幅と高さ
#define SCREEN_HEIGHT 240
#define MAGNIFICATION 2 // 倍率 = WINDOW_WIDTH / SCREEN_WIDTH
```

**Comment by dolphilia** [comment]
すみません、kikerogaさんのpaint命令のLinux動作報告を見逃していました。
入れ違いになってしまったかもしれませんが、今のところのTinyHSPは上記の通りです。

**Comment by kikeroga3** [comment]
イエイエ
解像度変更ですか、何とも大胆な(^^)
しかしながらローレゾも味わいがありますねぇ。

**Comment by kikeroga3** [comment]
GLFMとな。
https://github.com/brackeen/glfm

こんなの見つけたんですが、これモバイル版GLFWですかね？
Android-ndkからビルドできるって書いてあるのかしら？
なんかすごいのかも。

**Comment by dolphilia** [comment]
2ヶ月ぐらい前に、
TinyHSPのテーマ曲を作ろうとしたときの録音データが残っていたので、
特に理由はないのですが、アップしました。

[tinyhsp_theme_recording.mp3](https://dolphilia.com/wp-content/uploads/tinyhsp_theme_recording.mp3)

矩形波が耳にキツイので、
普通にピアノの音色で録音すれば良かったかなあ、とちょっと後悔。

・・・・・・

というわけで、さっき録り直したのがこちら。

[tinyhsp_theme_recording_piano.mp3](https://dolphilia.com/wp-content/uploads/tinyhsp_theme_recording_piano.mp3)

あちこちでミスタッチが目立ちますね。;^^

・・・・・・

さらに余談ですが、
CleanHSPをイメージした曲もあります。

[shokanokaze.mp3](https://dolphilia.com/wp-content/uploads/shokanokaze.mp3)

もうHSPのイメージからかけ離れすぎていて、
イメージ曲としては完全にボツでした。

今は普通のピアノ曲として公開しています。

---

まともなコメントが書けなくてすみません。;^^

**Comment by kikeroga3** [comment]
矩形波はインプリンティングされてて懐かしさを覚えるので、キライではない音源です(^^)
それにしてもプログラム言語のイメージ曲を作られるとは…やはりdolphiliaさんは只者ではありませんね。
CleanHSPの曲はクリーンな感じはばっちり伝わってきましたですヨ(^^)b

ところで「glfm.h」をざぁーっと眺めてみましたが「glfw3.h」と
それほど関数が対似しているワケでもなさそうです。
glfwGetKey → glfmGetKey くらいの修正で済めばコリャモウ最高だ！
とか思ってたんですが、さすがにそんなことはありませんでした。
